
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ github.sha }}
      - run: ./mvnw clean install -e -B -V
  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [ '8', '21' ]
        maven: [ '3.6.3', '3.8.8', '3.9.6' ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ github.sha }}
      - run: ./mvnw -e -B -V -Dmaven=${{ matrix.maven }} -Dtype=only-script wrapper:wrapper
      - run: ./mvnw -f its verify -e -B -V
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: its-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.maven }}
          path: ./its/target/classes/its
